import Foundation

/// Two-frame 64×64 synthetic HEVC encodes, not copyrighted source media.
/// Generated by AetherEngine's Scripts/make-hdr10plus-fixture.py; retained from
/// its HDR10PlusProbeIntegrationTests at f55789d746a723665ed9e096ef06102d248ae2a4.
/// These exercise the public engine API, not a second parser implementation.
enum HDR10PlusTestFixture {
    static var positive: Data { decode(positiveBase64) }
    static var plain: Data { decode(plainBase64) }

    /// 160 ordinary HDR10 HEVC keyframes, with real EAC3 packets interleaved
    /// after three seconds. Delaying audio keeps find_stream_info from confirming
    /// its JOC flag before the explicit Atmos pass. The old 128-video HDR budget
    /// exhausted the whole-probe packet budget before that pass could run.
    static var interleavedHDR10WithLateJOC: Data {
        interleaved(carriesHDR10Plus: false, plainAudioPacketCount: 0)
    }

    /// HDR10+ confirms on the first video packet, but the first 12 EAC3 packets
    /// are non-JOC. The decoder must keep scanning to audio packet 13.
    static var interleavedHDR10PlusWithJOCOnAudioPacket13: Data {
        interleaved(carriesHDR10Plus: true, plainAudioPacketCount: 12)
    }

    private static func interleaved(carriesHDR10Plus: Bool, plainAudioPacketCount: Int) -> Data {
        let mp4 = carriesHDR10Plus ? positive : plain
        func payload(_ type: String) -> Data {
            let name = mp4.range(of: Data(type.utf8))!
            let sizeOffset = name.lowerBound - 4
            let size = mp4[sizeOffset..<name.lowerBound].reduce(0) { ($0 << 8) | Int($1) }
            return mp4.subdata(in: name.upperBound..<(sizeOffset + size))
        }
        let samples = payload("mdat")
        let sizes = payload("stsz")
        let fixedSampleSize = sizes[4..<8].reduce(0) { ($0 << 8) | Int($1) }
        let firstSampleSize = fixedSampleSize > 0
            ? fixedSampleSize : sizes[12..<16].reduce(0) { ($0 << 8) | Int($1) }
        let videoPacket = Data(samples.prefix(firstSampleSize))
        let jocPacket = decode(jocSignaledSilenceBase64)
        let plainPacket = decode(nonJOCSilenceBase64)

        func element(_ id: [UInt8], _ value: Data) -> Data {
            let width = (1...8).first { value.count < (1 << (7 * $0)) - 1 }!
            var size = (0..<width).reversed().map {
                UInt8(truncatingIfNeeded: value.count >> ($0 * 8))
            }
            size[0] |= UInt8(1 << (8 - width))
            return Data(id + size) + value
        }
        func integer(_ id: [UInt8], _ value: UInt64) -> Data {
            let width = max(1, (64 - value.leadingZeroBitCount + 7) / 8)
            let bytes = (0..<width).reversed().map {
                UInt8(truncatingIfNeeded: value >> ($0 * 8))
            }
            return element(id, Data(bytes))
        }
        func floating(_ id: [UInt8], _ value: Double) -> Data {
            var bits = value.bitPattern.bigEndian
            return element(id, withUnsafeBytes(of: &bits) { Data($0) })
        }
        func block(track: UInt8, time: Int, packet: Data) -> Data {
            element([0xa3], Data([
                0x80 | track, UInt8(truncatingIfNeeded: time >> 8),
                UInt8(truncatingIfNeeded: time), 0x80
            ]) + packet)
        }
        let ebml = integer([0x42, 0x86], 1) + integer([0x42, 0xf7], 1)
            + integer([0x42, 0xf2], 4) + integer([0x42, 0xf3], 8)
            + element([0x42, 0x82], Data("matroska".utf8))
            + integer([0x42, 0x87], 4) + integer([0x42, 0x85], 2)
        let color = integer([0x55, 0xb1], 9) + integer([0x55, 0xb2], 10)
            + integer([0x55, 0xb9], 1) + integer([0x55, 0xba], 16)
            + integer([0x55, 0xbb], 9)
        let video = integer([0xb0], 64) + integer([0xba], 64)
            + element([0x55, 0xb0], color)
        let videoTrack = integer([0xd7], 1) + integer([0x73, 0xc5], 1)
            + integer([0x83], 1) + integer([0x88], 1)
            + integer([0x23, 0xe3, 0x83], 41_666_667)
            + element([0x86], Data("V_MPEGH/ISO/HEVC".utf8))
            + element([0x63, 0xa2], payload("hvcC")) + element([0xe0], video)
        let audio = floating([0xb5], 48_000) + integer([0x9f], 2)
        let audioTrack = integer([0xd7], 2) + integer([0x73, 0xc5], 2)
            + integer([0x83], 2) + integer([0x88], 1)
            + integer([0x23, 0xe3, 0x83], 32_000_000)
            + element([0x86], Data("A_EAC3".utf8)) + element([0xe1], audio)
        let tracks = element([0x16, 0x54, 0xae, 0x6b],
                             element([0xae], videoTrack) + element([0xae], audioTrack))
        let info = element([0x15, 0x49, 0xa9, 0x66],
                           integer([0x2a, 0xd7, 0xb1], 1_000_000)
                           + floating([0x44, 0x89], 160_000.0 / 24))
        var cluster = integer([0xe7], 0)
        for index in 0..<160 {
            let time = index * 1_000 / 24
            cluster += block(track: 1, time: time, packet: videoPacket)
            if index >= 72 {
                let audioPacket = index - 72 < plainAudioPacketCount ? plainPacket : jocPacket
                cluster += block(track: 2, time: time, packet: audioPacket)
            }
        }
        let segment = info + tracks + element([0x1f, 0x43, 0xb6, 0x75], cluster)
        return element([0x1a, 0x45, 0xdf, 0xa3], ebml) + element([0x18, 0x53, 0x80, 0x67], segment)
    }

    private static func decode(_ text: String) -> Data {
        Data(base64Encoded: text, options: .ignoreUnknownCharacters)!
    }

    /// One 260-byte CRC-correct silent EAC3 frame. Starting with the upstream
    /// AtmosDetectionProbeIntegrationTests ffmpeg-generated stereo silence:
    /// set addbsie at bit 53, insert addbsil=1, extension_type_a=1 and
    /// complexity_index_type_a=1 (22 bits), pad to an even frame size, update
    /// frmsiz, and regenerate CRC-16/ANSI over everything after the sync word.
    /// This tests the real decoder's JOC-profile signal, not spatial rendering
    /// or a copyrighted Dolby sample. No container Atmos declaration is added.
    private static let jocSignaledSilenceBase64 = """
    C3cAgTSHxBAQEACAAAABBgAAEBAQBAQEBj58+fPnz58+fPn3/Or58+fPnz58+fH/Or58+fPnz58+fAAAAAAN8+fPm222228ePHjwAAAAN8+fMm222228ePHjwAAAAAG+fPnzbbbbbePHjx4AAAAG+fPmTbbbbbePHjx4AAAAADfPnz5tttttvHjx48AAAADfPnzJtttttvHjx48AAAAABvnz58222223jx48eAAAABvnz5k222223jx48eAAAAAA3z58+bbbbbbx48ePAAAAA3z58ybbbbbbx48ePAAAAAAb58+fNttttt48ePHgAAAAb58+ZNttttt48ePHgAAAAAAAsDw=
    """

    /// The identical silent frame with extension_type_a cleared (bit 67) and
    /// CRC regenerated. Decoder profile must remain non-JOC on this prefix.
    private static let nonJOCSilenceBase64 = """
    C3cAgTSHxBAAEACAAAABBgAAEBAQBAQEBj58+fPnz58+fPn3/Or58+fPnz58+fH/Or58+fPnz58+fAAAAAAN8+fPm222228ePHjwAAAAN8+fMm222228ePHjwAAAAAG+fPnzbbbbbePHjx4AAAAG+fPmTbbbbbePHjx4AAAAADfPnz5tttttvHjx48AAAADfPnzJtttttvHjx48AAAAABvnz58222223jx48eAAAABvnz5k222223jx48eAAAAAA3z58+bbbbbbx48ePAAAAA3z58ybbbbbbx48ePAAAAAAb58+fNttttt48ePHgAAAAb58+ZNttttt48ePHgAAAAAAA4pY=
    """

    private static let positiveBase64 = """
    AAAAHGZ0eXBpc29tAAACAGlzb21pc28ybXA0MQAAAAhmcmVlAAAAwG1kYXQAAABFTgEEQLUAPAAB
    BABCYloAhNA+gB1MC7gkCA+gKB9AUC7gyE4hkH0CWLuC0PoC+RlDGTiAZE+hLCRkMhLGQfSWK8yD
    hACAAAAADigBr3jrrvv//FtlXy08AAAARU4BBEC1ADwAAQQAQmJaAITQPoAdTAu4JAgPoCgfQFAu
    4MhOIZB9Ali7gtD6AvkZQxk4gGRPoSwkZDISxkH0livMg4QAgAAAABAoAa8J4CQEyH//J2Eew0j8
    AAADw21vb3YAAABsbXZoZAAAAAAAAAAAAAAAAAAAA+gAAADIAAEAAAEAAAAAAAAAAAAAAAABAAAA
    AAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAIAAALtdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAQAAAAAAAADIAAAAAAAAAAAAAAAAAAAA
    AAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAABAAAAAQAAAAAAAJGVkdHMAAAAc
    ZWxzdAAAAAAAAAABAAAAyAAAAAAAAQAAAAACZW1kaWEAAAAgbWRoZAAAAAAAAAAAAAAAAAAST4AA
    A6mAVcQAAAAAAC1oZGxyAAAAAAAAAAB2aWRlAAAAAAAAAAAAAAAAVmlkZW9IYW5kbGVyAAAAAhBt
    aW5mAAAAFHZtaGQAAAABAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAA
    AAEAAAHQc3RibAAAAWRzdHNkAAAAAAAAAAEAAAFUaHZjMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAA
    AABAAEAASAAAAEgAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABj//wAA
    AMdodmNDAQQIAAAAnagAAAAAHvAA/P36+gAADwOgAAIAF0ABDAH//wQIAAADAJ2oAAADAAAeugJA
    ABdAAQwB//8ECAAAAwCdqAAAAwAAHroCQKEAAgArQgEBBAgAAAMAnagAAAMAAB6gIIEE2W6kkyvA
    WoSIBIIAAAMAAgAAAwAUEAArQgEBBAgAAAMAnagAAAMAAB6gIIEE2W6kkyvAWoSIBIIAAAMAAgAA
    AwAUEKIAAgAHRAHBcrAiQAAIRAHBcrAiQAAAAAATY29scm5jbHgACQAQAAkAAAAAEHBhc3AAAAAB
    AAAAAQAAABRidHJ0AAAAAAAAHMAAABzAAAAAGHN0dHMAAAAAAAAAAQAAAAIAAdTAAAAAHHN0c2MA
    AAAAAAAAAQAAAAEAAAACAAAAAQAAABxzdHN6AAAAAAAAAAAAAAACAAAAWwAAAF0AAAAUc3RjbwAA
    AAAAAAABAAAALAAAAGJ1ZHRhAAAAWm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAA
    AAAAAAAAAAAALWlsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZmNjIuMTIuMTAx
    """

    private static let plainBase64 = """
    AAAAHGZ0eXBpc29tAAACAGlzb21pc28ybXA0MQAAAAhmcmVlAAAALm1kYXQAAAAOKAGveOuu+//8
    W2VfLTwAAAAQKAGvCeAkBMh//ydhHsNI/AAAA8Ntb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPo
    AAAAyAABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAC7XRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAA
    AAEAAAAAAAAAyAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAA
    AEAAAAAAQAAAAEAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAAMgAAAAAAAEAAAAAAmVtZGlh
    AAAAIG1kaGQAAAAAAAAAAAAAAAAAEk+AAAOpgFXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAA
    AAAAAAAAAFZpZGVvSGFuZGxlcgAAAAIQbWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYA
    AAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAB0HN0YmwAAAFkc3RzZAAAAAAAAAABAAABVGh2
    YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAQABAAEgAAABIAAAAAAAAAAEAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAADHaHZjQwEECAAAAJ2oAAAAAB7wAPz9+voAAA8DoAAC
    ABdAAQwB//8ECAAAAwCdqAAAAwAAHroCQAAXQAEMAf//BAgAAAMAnagAAAMAAB66AkChAAIAK0IB
    AQQIAAADAJ2oAAADAAAeoCCBBNlupJMrwFqEiASCAAADAAIAAAMAFBAAK0IBAQQIAAADAJ2oAAAD
    AAAeoCCBBNlupJMrwFqEiASCAAADAAIAAAMAFBCiAAIAB0QBwXKwIkAACEQBwXKwIkAAAAAAE2Nv
    bHJuY2x4AAkAEAAJAAAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAAAAAAAXwAAAF8AAAABhzdHRz
    AAAAAAAAAAEAAAACAAHUwAAAABxzdHNjAAAAAAAAAAEAAAABAAAAAgAAAAEAAAAcc3RzegAAAAAA
    AAAAAAAAAgAAABIAAAAUAAAAFHN0Y28AAAAAAAAAAQAAACwAAABidWR0YQAAAFptZXRhAAAAAAAA
    ACFoZGxyAAAAAAAAAABtZGlyYXBwbAAAAAAAAAAAAAAAAC1pbHN0AAAAJal0b28AAAAdZGF0YQAA
    AAEAAAAATGF2ZjYyLjEyLjEwMQ==
    """
}
